export const Data = () => ([
  {
    NewsID: 399947,
    Company: {
      ID: 4602,
      Symbol: 'OVTI',
      Name: 'OmniVision Technologies, Inc.',
      ISIN: null,
      CIK: 1106851,
      TradeCount: 0,
      ViewCount: 0,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/OVTI/133223ff720046eabb37dfce600cb447.png',
    },
    Symbol: 'OVTI',
    Title: 'OmniVision Launches 1.55-Micron Large-Pixel PureCel?Plus-S Sensor for High-End Smartphones...',
    Content: null,
    Type: 1,
    Created: '2016-05-31T22:07:07.487',
    URL: 'http://www.ovt.com/release.php?release=376&lang=english',
    GeneratedURL: 'omnivision-launches-155micron-largepixel-purecelpluss-sensor-for-highend-smartphones-960',
    Duration: 'Just Now',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399962,
    Company: {
      ID: 7396,
      Symbol: 'NPD',
      Name: 'China Nepstar Chain Drugstore Ltd.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 136,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/NPD/0af0676cdeb24bd1943728a40511df0a.png',
    },
    Symbol: 'NPD',
    Title: 'China Nepstar Chain Drugstore Ltd. Reports First Quarter 2016 Financial Results',
    Content: null,
    Type: 1,
    Created: '2016-05-31T09:01:11.237',
    URL: 'http://ir.nepstar.cn/phoenix.zhtml?c=214790&p=irol-newsArticle&ID=2173323',
    GeneratedURL: 'china-nepstar-chain-drugstore-ltd-reports-first-quarter-2016-financial-results-147',
    Duration: '7 Minutes ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399961,
    Company: {
      ID: 3933,
      Symbol: 'HLIT',
      Name: 'Harmonic Inc.',
      ISIN: null,
      CIK: 851310,
      TradeCount: 0,
      ViewCount: 360,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/HLIT/a80e2988c811448a929f4c6dd81dc16a.png',
    },
    Symbol: 'HLIT',
    Title: 'ANGA COM 2016 Exhibitor Preview',
    Content: null,
    Type: 1,
    Created: '2016-05-31T08:39:10.913',
    URL: 'http://www.harmonicinc.com/news/anga-com-2016-exhibitor-preview',
    GeneratedURL: 'anga-com-2016-exhibitor-preview-354',
    Duration: '29 Minutes ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399960,
    Company: {
      ID: 4178,
      Symbol: 'JAZZ',
      Name: 'Jazz Pharmaceuticals plc',
      ISIN: null,
      CIK: 1232524,
      TradeCount: 0,
      ViewCount: 190,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/JAZZ/88b9015a9fe946d7af8dc778345997e8.png',
    },
    Symbol: 'JAZZ',
    Title:
      'Jazz Pharmaceuticals And Celator Pharmaceuticals Announce Agreement For Jazz Pharmaceuticals To Acquire Celator For $30.25 Per Share',
    Content: null,
    Type: 1,
    Created: '2016-05-31T07:35:05.627',
    URL: 'http://investor.jazzpharma.com/phoenix.zhtml?c=210227&p=irol-newsArticle&ID=2173319',
    GeneratedURL:
      'jazz-pharmaceuticals-and-celator-pharmaceuticals-announce-agreement-for-jazz-pharmaceuticals-to-acquire-celator-for-3025-per-share-233',
    Duration: '1 Hour ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399959,
    Company: {
      ID: 4222,
      Symbol: 'KONG',
      Name: 'KongZhong Corporation',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 294,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/KONG/3eafc94c8caa447496aa383d09e1bf58.png',
    },
    Symbol: 'KONG',
    Title: 'KongZhong to Announce First Quarter 2016 Financial Results on June 15, 2016',
    Content: null,
    Type: 1,
    Created: '2016-05-31T07:09:14.863',
    URL: 'http://ir.kongzhong.com/phoenix.zhtml?c=180513&p=irol-newsArticle&ID=2173314',
    GeneratedURL: 'kongzhong-to-announce-first-quarter-2016-financial-results-on-june-15-2016-760',
    Duration: '1 Hour ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399958,
    Company: {
      ID: 3161,
      Symbol: 'BRCD',
      Name: 'Brocade Communications Systems, Inc.',
      ISIN: null,
      CIK: 1009626,
      TradeCount: 0,
      ViewCount: 804,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/BRCD/4e80065dcbef4a50980f0ad5de6b8520.png',
    },
    Symbol: 'BRCD',
    Title: "Brocade at the Center of Mazenod College's Network Nervous System",
    Content: null,
    Type: 1,
    Created: '2016-05-31T07:02:09.443',
    URL:
      'http://newsroom.brocade.com/press-releases/brocade-at-the-center-of-mazenod-college-s-network-nervous-system-nasdaq-brcd-1261713',
    GeneratedURL: 'brocade-at-the-center-of-mazenod-college-network-nervous-system-560',
    Duration: '2 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399955,
    Company: {
      ID: 28842,
      Symbol: 'VOG',
      Name: 'Voyager Oil & Gas, Inc.',
      ISIN: null,
      CIK: 1283843,
      TradeCount: 0,
      ViewCount: 99,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/VOG/a35c05a887b141779486dce2524eea11.png',
    },
    Symbol: 'VOG',
    Title: 'Results for the 7-month period ended 31 December 2015',
    Content: null,
    Type: 1,
    Created: '2016-05-31T06:26:52.573',
    URL: 'http://www.victoriaoilandgas.com/investors/news/results-7-month-period-ended-31-december-2015',
    GeneratedURL: 'results-for-the-7month-period-ended-31-december-2015-482',
    Duration: '2 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399954,
    Company: {
      ID: 4463,
      Symbol: 'MTSC',
      Name: 'MTS Systems Corporation',
      ISIN: null,
      CIK: 68709,
      TradeCount: 0,
      ViewCount: 129,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MTSC/ab4b058ef60244fabfc981a13a7be0f4.png',
    },
    Symbol: 'MTSC',
    Title: 'Automotive Testing Show & Expo',
    Content: null,
    Type: 1,
    Created: '2016-05-31T06:12:58.497',
    URL: 'http://www.testingshow.com/brazil/',
    GeneratedURL: 'automotive-testing-show--expo-966',
    Duration: '2 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399953,
    Company: {
      ID: 3565,
      Symbol: 'DSPG',
      Name: 'DSP Group, Inc.',
      ISIN: null,
      CIK: 915778,
      TradeCount: 0,
      ViewCount: 286,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/DSPG/269b867b56b04916874390526e260507.png',
    },
    Symbol: 'DSPG',
    Title: 'DSP Group ULE Solutions Enable Effective Rodent Control',
    Content: null,
    Type: 1,
    Created: '2016-05-31T06:06:59.277',
    URL: 'http://ir.dspg.com/phoenix.zhtml?c=101665&p=irol-newsArticle&ID=2173292',
    GeneratedURL: 'dsp-group-ule-solutions-enable-effective-rodent-control-877',
    Duration: '3 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399952,
    Company: {
      ID: 31714,
      Symbol: 'PRGO',
      Name: 'Perrigo Co.',
      ISIN: null,
      CIK: 820096,
      TradeCount: 2,
      ViewCount: 1581,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/PRGO/db6f3e4cee714820bb0213e696ca9fbb.png',
    },
    Symbol: 'PRGO',
    Title: 'Perrigo Announces FDA Approval And Launch Of The Store Brand Equivalent To Flonase®',
    Content: null,
    Type: 1,
    Created: '2016-05-31T06:05:48.437',
    URL:
      'http://perrigo.investorroom.com/2016-05-31-Perrigo-Announces-FDA-Approval-And-Launch-Of-The-Store-Brand-Equivalent-To-Flonase',
    GeneratedURL: 'perrigo-announces-fda-approval-and-launch-of-the-store-brand-equivalent-to-flonase-248',
    Duration: '3 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399951,
    Company: {
      ID: 5291,
      Symbol: 'TIVO',
      Name: 'TiVo Inc.',
      ISIN: null,
      CIK: 1088825,
      TradeCount: 0,
      ViewCount: 322,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/TIVO/f14da5e9b0bf463b94a13e5593a44a8b.png',
    },
    Symbol: 'TIVO',
    Title: "TiVo's Cubiware Announces Integration With ALi Corp",
    Content: null,
    Type: 1,
    Created: '2016-05-31T01:30:03.85',
    URL: 'http://investor.tivo.com/phoenix.zhtml?c=106292&p=irol-newsArticle&ID=2173278',
    GeneratedURL: 'tivo-cubiware-announces-integration-with-ali-corp-825',
    Duration: '7 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399944,
    Company: {
      ID: 3610,
      Symbol: 'EFII',
      Name: 'Electronics for Imaging, Inc.',
      ISIN: null,
      CIK: 867374,
      TradeCount: 0,
      ViewCount: 596,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/EFII/8a80f8c57a434fb496f4afc2a6934226.png',
    },
    Symbol: 'EFII',
    Title: 'EFI Launches a Revolutionary Single-Pass Inkjet Press for High-Speed Corrugated Board Production',
    Content: null,
    Type: 1,
    Created: '2016-05-30T20:01:38.507',
    URL: 'http://ir.efi.com/releasedetail.cfm?ReleaseID=973299',
    GeneratedURL: 'efi-launches-a-revolutionary-singlepass-inkjet-press-for-highspeed-corrugated-board-production-363',
    Duration: '13 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399943,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Announces the Date of the Extraordinary General Meeting of Shareholders',
    Content: null,
    Type: 1,
    Created: '2016-05-30T19:31:57.917',
    URL: 'http://www.mtsgsm.com/news/2009-08-18-27649',
    GeneratedURL: 'mts-announces-the-date-of-the-extraordinary-general-meeting-of-shareholders-491',
    Duration: '13 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399942,
    Company: {
      ID: 5405,
      Symbol: 'VGIT',
      Name: 'Vanguard Intermediate -Term Government Bond ETF',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 4892,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/VGIT/f90213c6bb314286bf65d13b10cb5754.png',
    },
    Symbol: 'VGIT',
    Title: 'The U.S. Consumer Finally Embraces Thrift -- and Dollar Stores',
    Content: null,
    Type: 1,
    Created: '2016-05-30T19:16:37.657',
    URL: 'http://www.thestreet.com/story/13588364/1/the-u-s-consumer-finally-embraces-thrift-and-dollar-stores.html',
    GeneratedURL: 'the-us-consumer-finally-embraces-thrift--and-dollar-stores-262',
    Duration: '13 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399941,
    Company: {
      ID: 5072,
      Symbol: 'SODA',
      Name: 'SodaStream International Ltd.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 261,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/SODA/c3b3b318a35f4a1cbd7d35c60a2e90ab.png',
    },
    Symbol: 'SODA',
    Title: 'SodaStream Launches Homemade Beer System',
    Content: null,
    Type: 1,
    Created: '2016-05-30T19:03:34.097',
    URL: 'http://sodastream.investorroom.com/2016-05-30-SodaStream-Launches-Homemade-Beer-System',
    GeneratedURL: 'sodastream-launches-homemade-beer-system-454',
    Duration: '14 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399938,
    Company: {
      ID: 4150,
      Symbol: 'IBB',
      Name: 'iShares NASDAQ Biotechnology Index Fund',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 5,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/IBB/f61feda84b0a4529b7689c72d885f7b7.png',
    },
    Symbol: 'IBB',
    Title: "Allergan, Bank of America and Monsanto: Doug Kass' Views",
    Content: null,
    Type: 1,
    Created: '2016-05-30T18:53:46.417',
    URL:
      'http://us.rd.yahoo.com/finance/external/tsmfe/SIG=137j3nnrl/*https://www.thestreet.com/story/13588917/1/allergan-bank-of-america-and-monsanto-doug-kass-views.html?puc=yahoo&cm_ven=YAHOO',
    GeneratedURL: 'allergan-bank-of-america-and-monsanto-doug-kass-views-844',
    Duration: '14 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399937,
    Company: {
      ID: 5405,
      Symbol: 'VGIT',
      Name: 'Vanguard Intermediate -Term Government Bond ETF',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 4892,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/VGIT/f90213c6bb314286bf65d13b10cb5754.png',
    },
    Symbol: 'VGIT',
    Title: 'How to Put Down Less Than 20% to Buy a Home and Avoid PMI',
    Content: null,
    Type: 1,
    Created: '2016-05-30T18:14:54.99',
    URL: 'http://www.thestreet.com/story/13581118/1/how-to-put-down-less-than-20-to-buy-a-home-and-avoid-pmi.html',
    GeneratedURL: 'how-to-put-down-less-than-20-to-buy-a-home-and-avoid-pmi-961',
    Duration: '14 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399936,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Ranked the Most Valuable Brand in Russia',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:57:22.403',
    URL: 'http://www.mtsgsm.com/news/2010-12-13-28512',
    GeneratedURL: 'mts-ranked-the-most-valuable-brand-in-russia-167',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399935,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'Head of Business Unit “MTS Russia” Aleksander Popovskiy Joins the GSMA Board',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:57:16.623',
    URL: 'http://www.mtsgsm.com/news/2010-12-16-28516',
    GeneratedURL: 'head-of-business-unit-mts-russia-aleksander-popovskiy-joins-the-gsma-board-940',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399934,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Receives Notice from the Ministry of Communications of Turkmenistan',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:57:08.497',
    URL: 'http://www.mtsgsm.com/news/2010-12-16-28518',
    GeneratedURL: 'mts-receives-notice-from-the-ministry-of-communications-of-turkmenistan-305',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399933,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Group Acquires Leading Alternative Operator in Novosibirsk',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:56:59.623',
    URL: 'http://www.mtsgsm.com/news/2010-12-21-28533',
    GeneratedURL: 'mts-group-acquires-leading-alternative-operator-in-novosibirsk-733',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399932,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'Ministry of Communications of Turkmenistan Suspends MTS’ Operations',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:56:53.303',
    URL: 'http://www.mtsgsm.com/news/2010-12-21-28536',
    GeneratedURL: 'ministry-of-communications-of-turkmenistan-suspends-mts-operations-669',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399931,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Group Acquires Alternative Operator in Saint Petersburg',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:56:45.707',
    URL: 'http://www.mtsgsm.com/news/2010-12-24-28546',
    GeneratedURL: 'mts-group-acquires-alternative-operator-in-saint-petersburg-401',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399930,
    Company: {
      ID: 5962,
      Symbol: 'MBT',
      Name: 'Mobile Telesystems',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 1117,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MBT/a10d7021f78043378271952aa468f603.png',
    },
    Symbol: 'MBT',
    Title: 'MTS Completes Acquisition of Sistema Telecom',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:56:40.147',
    URL: 'http://www.mtsgsm.com/news/2010-12-27-28547',
    GeneratedURL: 'mts-completes-acquisition-of-sistema-telecom-644',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399929,
    Company: {
      ID: 6924,
      Symbol: 'MTL',
      Name: 'Mechel OAO',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 332,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MTL/96fb3b9e283e4c8db0aa42be35cb90fc.png',
    },
    Symbol: 'MTL',
    Title: 'Mechel Reports Decisions of its Extraordinary General Meeting of Shareholders',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:15:36.27',
    URL: 'http://www.mechel.com/press/press?rid=25062&oo=1&fnid=68&newWin=0&apage=1&nm=121929&fxsl=view_soc.xsl',
    GeneratedURL: 'mechel-reports-decisions-of-its-extraordinary-general-meeting-of-shareholders-940',
    Duration: '16 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399927,
    Company: {
      ID: 30620,
      Symbol: 'MC',
      Name: 'Moelis & Company',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 141,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MC/644a662ebb0f40debbfc94302de73915.png',
    },
    Symbol: 'MC',
    Title: 'LVMH · 05.30.2016\n Green Week: Investing for greener cities ',
    Content: null,
    Type: 1,
    Created: '2016-05-30T16:03:04.973',
    URL: 'https://www.lvmh.com/news-documents/news/green-week-investing-for-greener-cities/',
    GeneratedURL: 'lvmh-middot-05302016-green-week-investing-for-greener-citiesnbsp-426',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399925,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'Cloud enables international growth for businesses in Hong Kong and Singapore',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:47.663',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16.shtml',
    GeneratedURL: 'cloud-enables-international-growth-for-businesses-in-hong-kong-and-singapore-514',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399924,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'Image Mission streamlines operations with NetSuite to support exponential growth',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:37.49',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16a.shtml',
    GeneratedURL: 'image-mission-streamlines-operations-with-netsuite-to-support-exponential-growth-415',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399923,
    Company: {
      ID: 6156,
      Symbol: 'STM',
      Name: 'STMicroelectronics N.V.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 735,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/STM/21016096fa8445a687982bc5e4b7b5eb.png',
    },
    Symbol: 'STM',
    Title: 'Mobile World Congress Shanghai 2016',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:30.74',
    URL: 'http://www.st.com/content/st_com/en/about/events/events.html/mobile-world-congress-shanghai-2016.html',
    GeneratedURL: 'mobile-world-congress-shanghai-2016-981',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399922,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'Treknology Bikes 3 rides with NetSuite OneWorld to transform business operations',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:28.49',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16b.shtml',
    GeneratedURL: 'treknology-bikes-3-rides-with-netsuite-oneworld-to-transform-business-operations-570',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399921,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'NetSuite accelerates channel growth in Asia',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:16.553',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16c.shtml',
    GeneratedURL: 'netsuite-accelerates-channel-growth-in-asia-398',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399920,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'NetSuite OneWorld ready for Singapore and Hong Kong',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:14:00.383',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16d.shtml',
    GeneratedURL: 'netsuite-oneworld-ready-for-singapore-and-hong-kong-702',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399919,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'Cosmosupplylab implements NetSuite OneWorld to accelerate growth',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:13:48.4',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16e.shtml',
    GeneratedURL: 'cosmosupplylab-implements-netsuite-oneworld-to-accelerate-growth-932',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399918,
    Company: {
      ID: 6640,
      Symbol: 'N',
      Name: 'NetSuite Inc.',
      ISIN: null,
      CIK: 1117106,
      TradeCount: 0,
      ViewCount: 992,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/N/580355c274f8449ebab5482bb8024a23.png',
    },
    Symbol: 'N',
    Title: 'NetSuite accelarates business growth in asia',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:13:33.15',
    URL: 'http://www.netsuite.com/portal/company/pressreleases/05-30-16g.shtml',
    GeneratedURL: 'netsuite-accelarates-business-growth-in-asia-944',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399917,
    Company: {
      ID: 5635,
      Symbol: 'TD',
      Name: 'Toronto-Dominion Bank',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 588,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/TD/0f41a13f86c44de388ab7dd5889e12e3.png',
    },
    Symbol: 'TD',
    Title:
      'Media Advisory / Interview and Photo Opportunity - 20 Canadian students awarded more than $1.4 million in scholarships for outstanding achievements in community leadership',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:13:19.65',
    URL:
      'http://td.mediaroom.com/2016-05-30-Media-Advisory-Interview-and-Photo-Opportunity-20-Canadian-students-awarded-more-than-1-4-million-in-scholarships-for-outstanding-achievements-in-community-leadership',
    GeneratedURL:
      'media-advisory--interview-and-photo-opportunity--20-canadian-students-awarded-more-than-14-million-in-scholarships-for-outstanding-achievements-in-community-leadership-277',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399916,
    Company: {
      ID: 32798,
      Symbol: 'KKR',
      Name: 'Kohlberg Kravis Roberts & Co.',
      ISIN: null,
      CIK: 1404912,
      TradeCount: 0,
      ViewCount: 740,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/KKR/7bfd4b6b93f64602b862da22a3ea8be7.png',
    },
    Symbol: 'KKR',
    Title: 'Rob Yang Joins KKR as Managing Director to Lead Greater China Real Estate Platform',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:13:13.323',
    URL: 'http://ir.kkr.com/kkr_ir/kkr_releasedetail.cfm?ReleaseID=973277',
    GeneratedURL: 'rob-yang-joins-kkr-as-managing-director-to-lead-greater-china-real-estate-platform-790',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399915,
    Company: {
      ID: 30455,
      Symbol: 'LXFT',
      Name: 'Luxoft Holding, Inc. ',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 97,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/LXFT/c8044c344a0d4446b2db2ceb8697eb22.png',
    },
    Symbol: 'LXFT',
    Title: 'Luxoft Invests in Warsaw Adding New IT jobs in Poland ',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:13:03.777',
    URL: 'http://www.luxoft.com/pr/luxoft-invests-in-warsaw-adding-new-it-jobs-in-poland/',
    GeneratedURL: 'luxoft-invests-in-warsaw-adding-new-it-jobs-in-polandnbsp-725',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399914,
    Company: {
      ID: 6433,
      Symbol: 'CBT',
      Name: 'Cabot Corp.',
      ISIN: null,
      CIK: 16040,
      TradeCount: 0,
      ViewCount: 295,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/CBT/a3c70169c0204aaba898d40376c62bc7.png',
    },
    Symbol: 'CBT',
    Title: 'Cabot Norit Activated Carbon to Showcase Activated Carbon Products at IFAT 2016',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:12:43.26',
    URL: 'http://investor.cabot-corp.com/phoenix.zhtml?c=94559&p=irol-newsArticle&ID=2173244',
    GeneratedURL: 'cabot-norit-activated-carbon-to-showcase-activated-carbon-products-at-ifat-2016-978',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399911,
    Company: {
      ID: 4877,
      Symbol: 'RDHL',
      Name: 'Redhill Biopharma Ltd.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 744,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/RDHL/813850ceefe7432889e5971537e57d90.png',
    },
    Symbol: 'RDHL',
    Title: 'RedHill Biopharma to Present at Jefferies 2016 Healthcare Conference',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:12:13.137',
    URL: 'http://ir.redhillbio.com/releasedetail.cfm?ReleaseID=973290',
    GeneratedURL: 'redhill-biopharma-to-present-at-jefferies-2016-healthcare-conference-922',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399909,
    Company: {
      ID: 6400,
      Symbol: 'R',
      Name: 'Ryder System Inc.',
      ISIN: null,
      CIK: 85961,
      TradeCount: 0,
      ViewCount: 1071,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/R/c8da180da99c47d7ba6454bad75cee38.png',
    },
    Symbol: 'R',
    Title: 'Ryder Named a Most Valuable Employer for Military® by CivilianJobs.com for Fourth Year in a Row',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:33.2',
    URL:
      'http://newsroom.ryder.com/press-release/awards-recognition/ryder-named-most-valuable-employer-military-civilianjobscom-fourth-',
    GeneratedURL: 'ryder-named-a-most-valuable-employer-for-military-by-civilianjobscom-for-fourth-year-in-a-row-362',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399908,
    Company: {
      ID: 3635,
      Symbol: 'ENPH',
      Name: 'Enphase Energy, Inc.',
      ISIN: null,
      CIK: 1463101,
      TradeCount: 0,
      ViewCount: 767,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/ENPH/f52c0a23cab1443db8f41a47f81750d7.png',
    },
    Symbol: 'ENPH',
    Title: 'Enphase Energy Receives TOP PV Brand Netherlands 2016 Seal From EuPD Research',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:33.057',
    URL: 'http://investor.enphase.com/releasedetail.cfm?ReleaseID=973289',
    GeneratedURL: 'enphase-energy-receives-top-pv-brand-netherlands-2016-seal-from-eupd-research-666',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399907,
    Company: {
      ID: 28766,
      Symbol: 'RNO',
      Name: 'Rhino Resource Partners LP',
      ISIN: null,
      CIK: 1490630,
      TradeCount: 0,
      ViewCount: 523,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/RNO/4bd05faced9b41b5a750711780d87779.png',
    },
    Symbol: 'RNO',
    Title: 'Renault takes to the track in the World Academic Sport Challenge',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:33.01',
    URL: 'http://media.renault.com/global/en-gb/renaultgroup/Media/PressRelease.aspx?mediaid=78804&nodeid=-1 ',
    GeneratedURL: 'renault-takes-to-the-track-in-the-world-academic-sport-challenge-638',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399910,
    Company: {
      ID: 6284,
      Symbol: 'IT',
      Name: 'Gartner Inc.',
      ISIN: null,
      CIK: 749251,
      TradeCount: 0,
      ViewCount: 2162,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/IT/8f9356f1002c46fd9bc472650faf3389.png',
    },
    Symbol: 'IT',
    Title: 'The Key to Business Transformation is Culture',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:33.01',
    URL: 'http://gartner.com/smarterwithgartner/the-key-to-business-transformation-is-culture/',
    GeneratedURL: 'the-key-to-business-transformation-is-culture-638',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399906,
    Company: {
      ID: 5632,
      Symbol: 'MTU',
      Name: 'Mitsubishi UFJ Financial Group Inc.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 88,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/MTU/5ef10f20ebd14d5e8266fb70ad8e9629.png',
    },
    Symbol: 'MTU',
    Title: 'Redemption of “Non-dilutive” Preferred Securities Issued by Subsidiary',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:32.607',
    URL: 'http://www.mufg.jp/english/vcms_lf/news/pressrelease-20160530-001-e.pdf',
    GeneratedURL: 'redemption-of-nondilutive-preferred-securities-issued-by-subsidiary-973',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399904,
    Company: {
      ID: 5967,
      Symbol: 'COL',
      Name: 'Rockwell Collins Inc.',
      ISIN: null,
      CIK: 1137411,
      TradeCount: 0,
      ViewCount: 937,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/COL/7816d14b9f04447585a88d9cbe190ce4.png',
    },
    Symbol: 'COL',
    Title: 'Silver Star for a humble hero',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:11:17.573',
    URL: 'http://www.rockwellcollins.com/Data/Success_Stories/Our-Story/2016-Cal-Yr/Silver-star-hero.aspx',
    GeneratedURL: 'silver-star-for-a-humble-hero-456',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399901,
    Company: {
      ID: 30449,
      Symbol: 'LITB',
      Name: 'LIGHTINTHEBOX HOLDING CO., LTD',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 188,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/LITB/a612d158dadb4ff7bf4e715173990c93.png',
    },
    Symbol: 'LITB',
    Title: 'LightInTheBox Holding Co., Ltd. to Report First Quarter 2016 Financial Results on Monday, June 13, 2016',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:10:44.45',
    URL: 'http://ir.lightinthebox.com/phoenix.zhtml?c=251137&p=irol-newsArticle&ID=2173263',
    GeneratedURL:
      'lightinthebox-holding-co-ltd-to-report-first-quarter-2016-financial-results-on-monday-june-13-2016-151',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399903,
    Company: {
      ID: 5616,
      Symbol: 'VZ',
      Name: 'Verizon Communications Inc.',
      ISIN: null,
      CIK: 732712,
      TradeCount: 0,
      ViewCount: 243,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/VZ/167d0fe9492045e4a98baf5fb346d959.png',
    },
    Symbol: 'VZ',
    Title: 'Verizon reaches tentative agreements with unions representing wireline employees',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:10:44.45',
    URL:
      'http://newscenter.verizon.com/about/news/verizon-reaches-tentative-agreements-unions-representing-wireline-employees',
    GeneratedURL: 'verizon-reaches-tentative-agreements-with-unions-representing-wireline-employees-151',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399905,
    Company: {
      ID: 6777,
      Symbol: 'SMI',
      Name: 'Semiconductor Manufacturing International Corp.',
      ISIN: null,
      CIK: null,
      TradeCount: 0,
      ViewCount: 309,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/SMI/48252d123bdc47cb80ca45ad208b5329.png',
    },
    Symbol: 'SMI',
    Title: 'SMIC Announces its Fourth Donation of 2.55 Million Yuan for "Liver Transplant Program for Children"',
    Content: null,
    Type: 1,
    Created: '2016-05-30T15:10:12.543',
    URL: 'http://www.smics.com/eng/press/press_releases_details.php?id=362261',
    GeneratedURL:
      'smic-announces-its-fourth-donation-of-255-million-yuan-for-liver-transplant-program-for-children-599',
    Duration: '17 Hours ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399857,
    Company: {
      ID: 7144,
      Symbol: 'SSP',
      Name: 'E.W. Scripps Co. Cl A',
      ISIN: null,
      CIK: 832428,
      TradeCount: 0,
      ViewCount: 288,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/SSP/f852b5e6693f430fa1f8a23a42c960be.png',
    },
    Symbol: 'SSP',
    Title: 'NEWSCHANNEL 5 INVESTIGATORS EARN TOP HONORS FROM THE OHIO SPJ',
    Content: null,
    Type: 1,
    Created: '2016-05-30T01:28:28.623',
    URL: 'http://www.scripps.com/press-releases/691-newschannel-5-investigators-earn-top-honors-from-the-ohio-spj',
    GeneratedURL: 'newschannel-5-investigators-earn-top-honors-from-the-ohio-spj-583',
    Duration: '1 Day ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
  {
    NewsID: 399856,
    Company: {
      ID: 7144,
      Symbol: 'SSP',
      Name: 'E.W. Scripps Co. Cl A',
      ISIN: null,
      CIK: 832428,
      TradeCount: 0,
      ViewCount: 288,
      Stock: null,
      Stream: null,
      LogoPath: '/temp/SSP/f852b5e6693f430fa1f8a23a42c960be.png',
    },
    Symbol: 'SSP',
    Title: 'NBC ACTION NEWS AT 10 P.M. NAMED BEST PRIMETIME NEWSCAST BY THE KANSAS ASSOCIATION OF BROADCASTERS',
    Content: null,
    Type: 1,
    Created: '2016-05-30T01:15:47.987',
    URL:
      'http://www.scripps.com/press-releases/693-nbc-action-news-at-10-pm-named-best-primetime-newscast-by-the-kansas-association-of-broadcasters',
    GeneratedURL:
      'nbc-action-news-at-10-pm-named-best-primetime-newscast-by-the-kansas-association-of-broadcasters-804',
    Duration: '1 Day ago',
    Comments: [],
    Likes: [],
    LikesCount: 0,
    DislikesCount: 0,
    CommentsCount: 0,
  },
]);
